cc_binary(
    name = "main",
    srcs = ["main.cpp"],
    defines = ["NDEBUG"],
    deps = ["@glfw", "@glm", "@vulkan"],
)

cc_binary(
    name = "debug",
    srcs = ["main.cpp"],
    deps = ["@glfw", "@glm", "@vulkan"],
)